system {
    host-name edge-router-01;
    services {
        ssh;
    }
    ntp {
        server 10.10.10.10;
    }
    syslog {
        host 10.10.20.20 {
            any info;
        }
    }
}

snmp {
    community public {
        authorization read-only;
    }
}